{{- with .Values.hpa }}
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ .name }}
  namespace: {{ $.Release.Namespace | quote }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: {{ .scaleTargetRef.kind | default "Deployment" }}
    name: {{ .scaleTargetRef.name }}
  minReplicas: {{ .minReplicas | default 1 }}
  maxReplicas: {{ .maxReplicas | default 2 }}
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
      - periodSeconds: 60
        type: Pods
        value: 2
      - periodSeconds: 60
        type:  Percent
        value: 30
      selectPolicy: Min
    scaleUp:
      stabilizationWindowSeconds: 0
      policies:
        - type: Percent
          value: 100
          periodSeconds: 15
        - type: Pods
          value: 4
          periodSeconds: 15
          selectPolicy: Max
  metrics:
    {{- if not (empty .targetCPU) }}
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .targetCPU }}
    {{- end }}
    {{- if not (empty .targetMemory) }}
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ .targetMemory }}
    {{- end }}
{{- end }}