{{- range .Values.infisicalSecrets }}
---
apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  # Name of of this InfisicalSecret resource
  name: {{ .name }}
spec:
  # The host that should be used to pull secrets from. If left empty, the value specified in Global configuration will be used
  hostAPI: https://app.infisical.com/api
  resyncInterval: {{ .resyncInterval | default 60 }}
  authentication:
    serviceToken:
      serviceTokenSecretReference:
        secretName: {{ .serviceTokenSecretName }}
        secretNamespace: {{ .serviceTokenSecretNamespace | default "default" }}
      secretsScope:
        envSlug: {{ .env | default "prod" }}
        secretsPath: {{ .secretsPath }}
  managedSecretReference:
    secretName: {{ .secretName }} # <-- the name of kubernetes secret that will be created
    secretNamespace: {{ $.Release.Namespace | quote }} # <-- where the kubernetes secret should be created
    secretType: {{ .secretType | default "Opaque" }}
{{- end }}