{{- range .Values.pvs }}
---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: {{ .name }}
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "helpers.app.labels" $ | nindent 4 }}
    {{- with .labels }}{{- include "helpers.tplvalues.render" (dict "value" . "context" $) | nindent 4 }}{{- end }}
    type: local
  annotations:
    {{- with .annotations }}{{- include "helpers.tplvalues.render" (dict "value" . "context" $) | nindent 4 }}{{- end }}
spec:
  storageClassName: {{ .storageClassName }}
  capacity:
    storage: {{ .size }}
  persistentVolumeReclaimPolicy: Delete
  accessModes: {{- include "helpers.tplvalues.render" ( dict "value" .accessModes "context" $ ) | nindent 4 }}
  hostPath:
    path: {{ .hostPath }}
{{- end }}