{{- with .Values.roleBinding }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .name }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ .roleName }}
subjects:
  - kind: ServiceAccount
    name: {{ .serviceAccountName }}
{{- end }}