{{- with .Values.storageClass }}
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ include "helpers.app.fullname" (dict "name" .name "context" $) }}
provisioner: {{ .provisioner }}
volumeBindingMode: {{ .volumeBindingMode }}
reclaimPolicy: {{ .reclaimPolicy }}
{{- end }}