{{- with .Values.storageClass }}
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ .name }}
provisioner: {{ .provisioner }}
volumeBindingMode: {{ .volumeBindingMode }}
reclaimPolicy: {{ .reclaimPolicy }}
{{- end }}